config/routes.rb
Happilabs3::Application.routes.draw do

  resources :products
  resources :reviews
  resources :charges

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users
  resources :reports
  resources :categories
	get "/categories_index" => "Categories#categories_index", as: "categories_index"
  resources :subscribers

  root to: "Pages#index"

  get "/contact" => "Pages#contact", as: "contact"
  get "/200ml" => "Pages#two_hundred_ml", as: "two_hundred_ml"
  get "/1000ml" => "Pages#one_thousand_ml", as: "one_thousand_ml"
  get "/our_people" => "Pages#our_people", as: "our_people"

  get "/jobs" => "Pages#jobs", as: "privacy_policy"
  get "/privacy_policy" => "Pages#privacy_policy", as: "privacy_policy"
  get "/user_agreement" => "Pages#user_agreement", as: "user_agreement"
  get "/lab_sustainability" => "Pages#lab_sustainability", as: "lab_sustainability"

  get "/index" => "Pages#index"
  get "/about_us" => "Pages#about_us", as: "about_us"
  get "/sign_up" => "Pages#sign_up", as: "sign_up"

  get "/voices" => "Pages#voices", as: "voices"
  match '/voices' => 'Pages#create_voice', :as => 'voices', :via => :post
  get "/user_voices" => "Pages#user_voices", :as => "user_voices"
  post "/user_voices" => "Pages#create_user_voice", :as => 'user_voices'
  get "/user_index" => "Pages#user_index", :as => "user_index"
  delete "/user_index/:user_id" => "Pages#delete_user", :as => "delete_user"

  get "/categories/:id/sorted_alphabetically" => "Categories#sorted_alphabetically", :as => "categories_sorted_alphabetically"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :fair_price, :price_quantity, :first_quality, :second_quality, :third_quality, :youtube, :hl_logo, :paying_photo

  has_many :products

  def products_sorted_by_average_product_rating
    product_array = self.products.map! { |product| product }
    product_array.sort_by {|product| product.reviews.average("rating").to_f}.reverse
  end

  def products_sorted_alphabetically
    product_array = self.products.map! { |product| product }
    product_array.sort_by {|product| product.manufacturer_name}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json

  before_filter :validate_admin, :except => [:index, :show, :product_list, :sorted_alphabetically]
  # before_filter :authenticate_user!, :only => [:show]

  def index
    @categories = Category.order("name ASC")
    @latest_reviews = Review.limit(3).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @categories = Category.order("name ASC")
    @product_list = @category.products_sorted_by_average_product_rating
    @review = Review.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  def sorted_alphabetically
    @category = Category.find(params[:id])
    @categories = Category.order("name ASC")
    @product_list = @category.products_sorted_alphabetically

    respond_to do |format|
      format.html { render "show" }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

	def categories_index
		@categories = Category.order("name ASC")
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field">
    <%= f.text_field :name, placeholder: "Category Name"  %>
  </div>

  <div class="field">
    <%= f.text_field :fair_price, placeholder: "Fair Price (Do not put dollar sign here)"  %>
  </div>

  <div class="field">
    <%= f.text_field :price_quantity, placeholder: "Price out of how many?"  %>
  </div>

  <div class="field">
    <%= f.text_field :first_quality, placeholder: "First quality to look for"  %>
  </div>

  <div class="field">
    <%= f.text_field :second_quality, placeholder: "Second quality to look for"  %>
  </div>

  <div class="field">
    <%= f.text_field :third_quality, placeholder: "Third quality to look for"  %>
  </div>

  <div class="field">
    <%= f.text_field :youtube, placeholder: "YouTube Video"  %>
  </div>

  <div class="field">
    <%= f.text_field :paying_photo, placeholder: "Photo (paying)"  %>
  </div>

  <div class="field">
    <%= f.text_field :hl_logo, placeholder: "Happilabs Logo"  %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/categories/_product.html.erb
<article class='manufacturer-preview'>
  <div class='man-preview-left'>

      <!-- <img src="../products/pipette100.png"> -->
      <p class='brand center'><%= product.manufacturer_name %></p>

      <dl class='name-description'>
        <!-- <dt><%= product.product_name %></dt> -->
        <dd><%= product.product_desc %></dd>
        <dd>Product #: <%= product.product_num %></dd>
      </dl>
  </div>

  <div class='man-preview-right center'>
      <dl class='rating'>
        <dt>RATING</dt>
      <% if product.reviews.present? %>
        <dd class="real-rating"><%= product.reviews.average("rating").round(1) %><span class="year"> /5.0</span></dd>
        <dd class='side-note'>(out of <%= product.reviews.count("rating") %> reviews)</dd>
      <% else %>
        <dd class="real-rating">0.0<span class="year"> /5.0</span></dd>
        <dd class='side-note'>(out of 0 reviews)</dd>
      <% end %>
      </dl>
      <div class="see-reviews-btn">
        <%= button_to "Explore reviews", product, class: "see-reviews-btn btn btn-info", method: :get %>
      </div>
  </div>
  <% if product.reviews.present? %>
    <p class="latest_review"><strong>Latest Review: </strong> "<%= product.reviews.last.desc %>"</p>
  <% end %>
</article>

app/views/categories/categories_index.html.erb
<div class="sky-background">
  <div class="container content-container grid group">

  <h1>Categories Index <%= link_to "Add a Category", new_category_path, class: "btn btn-primary" %></h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Fair Price ($)</th>
        <th>YouTube</th>
        <th>Edit</th>
				<th>Delete?</th>
      </tr>
    </thead>
    <tbody>
    <% @categories.each do |cat| %>
      <tr>
        <td><%= cat.id %></td>
        <td><%= link_to cat.name, category_path(cat.id) %></td>
        <td>$<%= cat.fair_price %> for <%= cat.price_quantity %> units</td>
        <td><%= cat.try(:youtube) %></td>
        <td><%= link_to "Edit ##{cat.id}", edit_category_path(cat.id) %></td>
        <td><%= link_to "Delete?", category_path(cat.id), method: :delete, confirm: "Are you sure?" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/categories/edit.html.erb
<div class="about-us grid">
  <div class="center">
		<h1>Editing category : <%= @category.name %></h1>
		
		<%= render 'form' %>
		
		<%= link_to 'Show', @category %> |
		<%= link_to 'Back', categories_index_path %>
  </div>
</div>

app/views/categories/index.html.erb
<div class='container group'>
  <div class="page-heading">
    <h2 class='container content-container'>Quality Ratings & Reviews</h2>
    <h4 class="container heading-liner">This is a forum where scientists can share their opinion about different brands of lab supplies.</h4>
  </div>

    <div id="" class="group">
        <!-- <div class="review-intro" class="group">
          <p><strong>Why is this important?</strong> Read the reports...</p>
            <ul>
              <li>Via <em>Science</em>: <a href="http://www.sciencemag.org/content/322/5903/917.short">Bioactive Contaminants Leach from Laboratory Plasticware</a></li>
              <li>Via <em>Nature</em>: <a href="http://www.nature.com/news/2010/100423/full/news.2010.200.html">Plastics Hamper DNA Assays</a></li>
            </ul>
        </div> -->

        <div class="review-intro group" id="review-why">

          <h2 id="how-it-works">How it works</h2>
            <ol>
              <li>Select a category of lab supplies</li>
              <li>Select a brand and read scientist's opinions or login to submit your own opinion (we are new, so there are not many reviews. Be one of the first!)</li>
              <li><%= link_to "200 µL subscribers", two_hundred_ml_path %> can view pricing data for each category</li>
            </ol>
        </div>

    </div>

  <%# unless user_signed_in? %>
    <!-- <section class="category-index-intro-box group">
      <h5>How to write a review</h5>
        <ul>
          <li>
              <span class="yellow-bold">Step 1: </span><span class="user-text-direction"><%= link_to "LOGIN", new_user_session_path %></span> OR <span class="user-text-direction"><%= link_to "SIGN UP", new_user_registration_path %></span>
          </li> -->
           <!--  <ul class="category-parent-li">

              <li><p class="center"><span class="user-text-direction">LOGIN</span></p></li>
              <li><p>OR</p></li>
              <li><p class="center"><span class="user-text-direction">SIGN UP</span></p></li>
            </ul> -->
        <!--   <li class="second-p"><span class="yellow-bold">Step 2:</span> Select a product</li>
          <li class="second-p"><span class="yellow-bold">Step 3:</span> Rate and review the product</li> -->
          <!-- <li class="second-p">To know which brands scientists like most, <p class="center">SELECT A CATEGORY...</span></p></li> -->
       <!--  </ul>
    </section> -->
  <%# end %>


    <section class='category-review-images group'>


      <div id="latest_reviews" >
        <center><h2 class="people-name">RECENT REVIEWS:</h2></br></center>
        <% @latest_reviews.each do |review| %>
          <span class="blue"><%= review.user.first_name %> from <%= review.user.organization %></br>
          about <%= review.product.category.name %></span></br>
        <span class="gray"><%= link_to review.desc, review.product, class: "sidebar-review" %></span></br><hr>
        <% end %>
      </div>

      <div class="category-section">
      <h2 class="people-name" id="yellow-heading">SELECT A CATEGORY</h2>
      <%# #TODO - add pictures to database & put dynamicness in below %>
      <ul>
        <li>
          <a href="<%= category_url(1) %>">
            <img src="products/pipette100.png" alt="pipette tip 10 happy reviews" title="scientific lab supply pipette tip review">
            10 ul tips
          </a>

        </li>
        <li>
          <a href="<%= category_url(2) %>">
            <img src="products/pipette200.png" alt="pipette tips 200 happy reviews" title="scientific lab supply pipette tip review">
           200 ul tips
          </a>
        </li>
        <li>
          <a href="<%= category_url(3) %>">
            <img src="products/pipette1000.png" alt="1000 pipette tip happy reviews" title="scientific lab supply pipette tip review">
            1000 ul tips
          </a>
        </li>
        <li>
          <a href="<%= category_url(4) %>">
            <img src="products/1.5ml_tube.png" alt="eppy microtube happy reviews" title="scientific lab supply eppy microtube review">
            1.5 mL microtube
          </a>
        </li>
        <li>
          <a href="<%= category_url(5) %>">
            <img src="products/15ml_conical_tube.png" alt="15 ml conical tube happy reviews" title="scientific lab supply 15ml conical tube review">
            15 mL conical tube
          </a>
        </li>
        <li>
          <a href="<%= category_url(6) %>">
            <img src="products/50ml_conical_tube.png" alt="50ml conical tube happy reviews" title="scientific lab supply conical tube review">50 mL conical tube
          </a>
        </li>
        <li>
          <a href="<%= category_url(8) %>">
            <img src="products/latex-glove_review.png" alt="latex gloves happy reviews" title="scientific lab supply latex gloves review">
            Latex gloves
          </a>
        </li>
        <li>
          <a href="<%= category_url(7) %>">
            <img src="products/nitrile_glove_review.png" alt="nitrile glove happy reviews" title="scientific lab supply nitrile glove review">
            Nitrile gloves
          </a>
        </li>

        <li>
          <a href="<%= category_url(11) %>">
            <img src="products/t75_flask2_review.png" alt="t75 flask cell culture happy reviews" title="scientific lab supply conical tube review">
            T75 flask
          </a>
        </li>
        <li>
          <a href="<%= category_url(12) %>">
            <img src="products/cell_culture_dish_review.png" alt="cell culture 100mm dish happy reviews" title="scientific lab supply 100mm dish review">
            100 mm dish
          </a>
        </li>
        <li>
          <a href="<%= category_url(9) %>">
            <img src="products/5ml_serological_pipet.png" alt="5ml serological pipet happy reviews" title="cell culture serological pipet review">
            5 mL serological pipet
          </a>
        </li>
        <li>
          <a href="<%= category_url(10) %>">
            <img src="products/10ml_serological_pipet.png" alt="10ml serological pipet happy reviews" title="cell culture 10ml serological pipet review">
            10 mL serological pipet
          </a>
        </li>
         <li>
          <a href="<%= category_url(14) %>">
            <img src="products/dome-pcr-tube.png" alt="dome cap pcr tube happy reviews" title="scientific lab supply pcr tube review">0.2 mL PCR tube
          </a>
        </li>
        <li>
          <a href="<%= category_url(15) %>">
            <img src="products/black-pcr-plate.png" alt="96 well pcr plate happy reviews" title="scientific lab supply pcr plate 96 wells review">96-well PCR Plates
          </a>
        </li>
        <li>
          <a href="<%= category_url(16) %>">
            <img src="products/genomic-dna-extraction-kit.png" alt="genomic dna extraction kit happy reviews" title="scientific lab supply genomic dna extraction kit reviews">Genomic DNA Extraction Kits
          </a>
        </li>
        <li>
          <a href="<%= category_url(17) %>">
            <img src="products/pcr-strip-tube.png" alt="genomic dna extraction kit happy reviews" title="scientific lab supply genomic dna extraction kit reviews">PCR 8-strip tubes
          </a>
        </li>
      </ul>
    </div>
    </section>
    <!-- <aside>
      <h3 class='center'>OUR MISSION</h3>
      <p>To improve the happiness of scientists &amp; the quality of theit research</p>
    </aside> -->
</div>

<script>
$(document).ready(function() {
  $('#nav_reviews').addClass('active');

  var reviews = document.getElementsByClassName("sidebar-review")
  for (var i = 0; i< reviews.length; i++)
    reviews[i].innerHTML = reviews[i].innerHTML.substring(0, 300) + "...";
});
</script>

app/views/categories/new.html.erb
<div class="about-us grid">
  <div class="center">
    <h1>New category</h1>

    <%= render 'form' %>

    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="small-grid about-us">
  <p id="notice"><%= notice %></p>

      <!-- <div class="page-heading">
        <h1>PRODUCT SUMMARIES</h1>
        <div class="contact-us">
          <p>The scientific community has problems that need solving.</p>
        </div>
      </div> -->


  <div class='container group'>


<!-- ***********   Product Menu   ***************-->


    <aside class='category-review-list'>
      <h4>Select a Category</h4>
      <ul>
      <% @categories.each do |cat| %>
        <% if cat.id == params[:id].to_i %>
        <li><%= link_to "#{cat.name}", category_url(cat.id), class: "category-review-list-selected" %></li>
        <% else %>
        <li><%= link_to "#{cat.name}", category_url(cat.id) %></li>
        <% end %>
      <% end %>
      </ul>
    </aside>


    <!-- ***********   Product Menu Ends  ***************-->

      <div class='selected-category-frame'>
          <div id="img-transparent">
            <% if @category.products.present? %>
            <img src=<%= @category.products.first.photo %>>
            <% end %>
          </div>

          <h1><%= @category.name %></h1>

          <a href="http://www.happilabs.org/200ml">
            <div id="category-frame-right">
              <h2>Fair price to pay: </h2>

                <% if current_user.try(:subcription_level) == "200" || current_user.try(:subcription_level) == "1000" %>
                <dl class='center'>

                  <dd>$<%= @category.fair_price %></dd>
                  <p class="quantity">per <%= @category.price_quantity %></p>
                </dl>
              <% else %>
              <dl class='center noprice-summary-text'>
                <p>Price data available with <strong>200ul SERVICE</strong></p>
              </dl>
              <% end %>

            </div>
          </a>

          <%# link_to "View on YouTube", @category.try(:youtube) %>
      </div>



    <section class='category-review-show group'>
      <% if user_signed_in? %>
        <div class="write-review-btn">
          <%= button_tag "Write a review", class: "btn btn-danger see-reviews-btn", id: "add_review_button" %>
        </div>

      <div id="big_review_form">
        <div class='selected-category-frame'>
        <!-- <h2>Write a review</h2> -->
          <%= form_for(@review) do |f| %>
            <% if @review.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@review.errors.count, "error") %> prevented this review from being saved:</h2>

                <ul>
                <% @review.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.hidden_field :user_id, :value => current_user.id %>
            </div>

            <div class="row">
              <div class="span3">
                <%= f.label :Brand %>
                <%= f.select :product_id, options_from_collection_for_select(Product.where(category_id: params[:id]), :id, :manufacturer_name) %>
              </div>
              <div class="span3">
                  <%= f.label :rating %>
                <%= f.select :rating, options_for_select([
                  ["5 Extremely happy (never a problem)", "5"],
                    ["4", "4"],
                    ["3 Neither happy nor unhappy", "3"],
                    ["2", "2"],
                    ["1 Extremely unhappy (frequent problems)", "1"]]) %>
              </div>
            </div>

            <div class="row">
              <div class="span3">
                <h5 class="blue no_margin">Features to review</h5>
                <li><%= @category.first_quality %></li>
                <li><%= @category.second_quality %></li>
                <li><%= @category.third_quality %></li>
              </div>
              <div class="span3">
                <!-- <%# f.label :desc, "Your Review:" %><br /> -->
                <%= f.text_area :desc, rows: 12 , placeholder: "Write your review here..." %>

              </div>

            </div>


            <br>

            <div class="actions">
              <%= f.submit :class => "btn btn-danger float-right button" %>
            </div>

          <% end %><!-- end review form -->
        </div>
      </div><!-- end #big_review_form -->
      <% end %>


      <!-- ****** Begin section for brands of products ******** -->

        <% unless user_signed_in? %>
          <div class="margin-left">
            <%= link_to "LOGIN to write a review", new_user_session_path, class: "see-reviews-btn btn btn-success" %>
          </div>
        <% end %>

      <h3 id="category-brand-title">Ratings & Reviews</h3>

          <% if request.fullpath.include?("sorted_alphabetically") %>
            <p class="sorted_products"><%= link_to "Sort by Rating", category_path %></p>
          <% else %>
            <p class="sorted_products"><%= link_to "Sort Alphabetically", categories_sorted_alphabetically_path %></p>
          <% end %>



          <% @product_list.each do |prod| %>
            <%= render "product", :product => prod %>
          <% end %>

          <h5 id="no-brand">Is your brand NOT listed? Send a message and we'll list it: <strong>hello@happilabs.org</strong>. Thank you for your patience as we continue to expand the site.</h5>
    </section>
  </div>
</div>

<script>
$(document).ready(function() {
 $('#nav_reviews').addClass('active');

 $('#big_review_form').hide();
 $("#add_review_button").click(function(){
   $("#big_review_form").fadeToggle("slow", "linear");
 });

});
</script>