config/routes.rb
Happilabs3::Application.routes.draw do

  resources :products
  resources :reviews
  resources :charges

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users
  resources :reports
  resources :categories
	get "/categories_index" => "Categories#categories_index", as: "categories_index"
  resources :subscribers

  root to: "Pages#index"

  get "/contact" => "Pages#contact", as: "contact"
  get "/200ml" => "Pages#two_hundred_ml", as: "two_hundred_ml"
  get "/1000ml" => "Pages#one_thousand_ml", as: "one_thousand_ml"
  get "/our_people" => "Pages#our_people", as: "our_people"

  get "/jobs" => "Pages#jobs", as: "privacy_policy"
  get "/privacy_policy" => "Pages#privacy_policy", as: "privacy_policy"
  get "/user_agreement" => "Pages#user_agreement", as: "user_agreement"
  get "/lab_sustainability" => "Pages#lab_sustainability", as: "lab_sustainability"

  get "/index" => "Pages#index"
  get "/about_us" => "Pages#about_us", as: "about_us"
  get "/sign_up" => "Pages#sign_up", as: "sign_up"

  get "/voices" => "Pages#voices", as: "voices"
  match '/voices' => 'Pages#create_voice', :as => 'voices', :via => :post
  get "/user_voices" => "Pages#user_voices", :as => "user_voices"
  post "/user_voices" => "Pages#create_user_voice", :as => 'user_voices'
  get "/user_index" => "Pages#user_index", :as => "user_index"
  delete "/user_index/:user_id" => "Pages#delete_user", :as => "delete_user"

  get "/categories/:id/sorted_alphabetically" => "Categories#sorted_alphabetically", :as => "categories_sorted_alphabetically"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :distributor_name, :manufacturer_name, :photo, :price, :product_desc, :product_name, :product_num, :recommended, :url

  belongs_to :category
  has_many :reviews

  def to_param
    "#{self.id}-#{self.product_name.parameterize}"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :validate_admin, :except => [:show]
  # before_filter :authenticate_user!, :only => [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.sort_by {|product| product.category_id}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @review = Review.new
    @reviews = Review.where(:product_id => params[:id])
    @categories = Category.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br />
    <%# f.number_field :category_id %>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :product_name, "Name" %><br />
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_desc, "Description" %><br />
    <%= f.text_area :product_desc, rows: 12 %>
  </div>
  <div class="field">
    <%= f.label :product_num, "Product Number" %><br />
    <%= f.text_field :product_num %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_name %><br />
    <%= f.text_field :manufacturer_name %>
  </div>
  <div class="field">
    <%= f.label :distributor_name %><br />
    <%= f.text_field :distributor_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :recommended, "Recommended?" %>
    <%= f.check_box :recommended %>
  </div>
  <br>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="about-us grid">
<h1>Editing product</h1>
<div class="center">
  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%# f.label :category_id %><br />
      <%# f.number_field :category_id %>
      <%# f.select :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
      <%= f.hidden_field :category_id, value: @product.category_id %>
    </div>
    <div class="field">
      <%= f.label :product_name, "Name" %><br />
      <%= f.text_field :product_name %>
    </div>
    <div class="field">
      <%= f.label :product_desc, "Description" %><br />
      <%= f.text_area :product_desc, rows: 12 %>
    </div>
    <div class="field">
      <%= f.label :product_num, "Product Number" %><br />
      <%= f.text_field :product_num %>
    </div>
    <div class="field">
      <%= f.label :photo %><br />
      <%= f.text_field :photo %>
    </div>
    <div class="field">
      <%= f.label :manufacturer_name %><br />
      <%= f.text_field :manufacturer_name %>
    </div>
    <div class="field">
      <%= f.label :distributor_name %><br />
      <%= f.text_field :distributor_name %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :recommended, "Recommended?" %>
      <%= f.check_box :recommended %>
    </div>
    <br>
    <div class="field">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-danger" %>
    </div>
  <% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>
</div>

app/views/products/index.html.erb
<div class="sky-background">
  <div class="content-container grid group">
    <h1>Product Index</h1>
        <table class="table table-striped">
          <tr>
            <th>Category</th>
            <th>Product name</th>
            <th>Product desc</th>
            <th>Product num</th>
            <th>Photo</th>
            <th>Manufacturer name</th>
            <th>distributor name</th>
            <th>Price</th>
            <th>Recommended</th>
            <th>Url</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

        <% @products.each do |product| %>
          <tr>
            <td><%= product.category.name %></td>
            <td><%= product.product_name %></td>
            <td><%= product.product_desc %></td>
            <td><%= product.product_num %></td>
            <td><%= link_to "photo", product.photo %></td>
            <td><%= product.manufacturer_name %></td>
            <td><%= product.distributor_name %></td>
            <td><%= product.price %></td>
            <td><%= product.recommended %></td>
            <td><%= product.url %></td>
            <td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </table>
        <br />
    </div>
</div>

app/views/products/new.html.erb
<div class="about-us grid">
  <div class="center">
  <h1>New product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<div class="small-grid">
<div id='header-fix'></div>

  <h2><%= @product.manufacturer_name %> Reviews</h2>
  <p id="notice"><%= notice %></p>

  <div class='container group'>

    <aside class='category-review-list'>
      <h4>Select a Product to Review</h4>
      <ul>
        <% @categories.each do |category| %>
          <% if category.id == Product.find_by_id(params[:id]).category.id.to_i %>
            <li><%= link_to category.name, category, class: "category-review-list-selected" %></li>
          <% else %>
            <li><%= link_to category.name, category %></li>
          <% end %>
        <% end %>
      </ul>
    </aside>

    <section class='show-page-content'>
      <article class='product-summary group'>
        <div>
          <!-- Alex, place that Ruby code right here :) -->
          <% if @product.photo.present? %>
            <img src="<%= @product.photo %>">
          <% end %>
          <p class='circle-note'>
            <b>Product #:</b>
            <%= @product.product_num %>
          </p>
        <!-- <p>
          <b>Photo:</b>
          <%= @product.photo %>
        </p> -->
        </div>

        <div>
          <!-- <h3><%= @product.manufacturer_name %></h3>
          <h4><%= @product.product_name %></h4> -->
          <div class="rating2">
            <h4>RATING</h4>
        <% if @product.reviews.present? %>
            <h1 class="real-rating2"><%= @product.reviews.average("rating").round(1) %><span class="year"> /5.0</span></h1>
            <p class='side-note-dark'>(out of <%= @product.reviews.count("rating")  %> reviews)</p>
        <% else %>
            <h1 class="real-rating2">0.0<span class="year"> /5.0</span></h1>
            <p class='side-note-dark'>(out of 0 reviews)</p>
        <% end %>
          </div>
        </div>
        <div>
          <!-- <p class='side-note-dark'>
            <b>Product num:</b>
            <%= @product.product_num %>
          </p> -->
          <% if current_user.try(:subcription_level) == "200" || current_user.try(:subcription_level) == "1000" %>
            <h5>Fair Price for academia:</h5>
            <h3><%= @product.price %></h3>
          <div class="noprice-summary-text">
          <% else %>
            <p><span id="fair-price-topay">What is a fair price?</span><br><span class="side-note-dark">Pricing Information available for 200µl or 1000µl services only</span></p>
          <% end %>
         <!--  Alex, the new product URL goes right here :) -->
          <a href="<%= @product.url if @product.url %>">Product Information</a>
          </div>
      </article>
    </section>


    <section class='all-reviews-container'>

      <% if current_user.present? %>
        <br>

        <div class="write-review-btn">
          <%= button_tag "+ Write a review for #{@product.product_name}", class: "btn btn-info see-reviews-btn", id: "product_show_review_button" %>
        </div>

        <br>
        <div id="product_show_review">
          <ul id="product_qualities">
            <h3 class="blue">Features to review:</h3>
            <li><%= @product.category.first_quality %></li>
            <li><%= @product.category.second_quality %></li>
            <li><%= @product.category.third_quality %></li>
          </ul>
          <%= form_for @review do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :product_id, :value => params[:id] %>
            <div class="field">
            <%= f.label :rating, "This brand makes me"%>
            <%= f.select :rating, options_for_select([
              ["5 Extremely happy (never a problem)", "5"],
              ["4", "4"],
              ["3 Neither happy nor unhappy", "3"],
              ["2", "2"],
              ["1 Extremely unhappy (frequent problems)", "1"]]) %>
            </div>
            <div class="field">
              <%= f.label :desc, "Write your review" %>
              <%= f.text_area :desc, rows: 6 %>
            </div>
            <br>
            <div class="actions">
              <%= f.submit :class => "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="write-review-btn">
        <%= link_to "Login to Write a Review", new_user_session_path, class: "btn btn-info see-reviews-btn" %>
        </div>
      <% end %>

      <% @reviews.reverse.each do |review| %>
      <article class='individual-review-container'>
        <% if current_user && current_user.try(:id) == review.user.id %>
        <p><%= review.rating %> / 5 | <%= review.updated_at.strftime("%B %d, %Y") %> (<%= link_to "edit", edit_review_url(review) %>/<%= link_to "delete", review , method: :delete, confirm: "Are you sure ou want to delete this review?" %>)</p>
        <% else %>
        <p><%= review.rating %> / 5 | <%= review.updated_at.strftime("%B %d, %Y") %></p>
        <% end %>
        <p><b>Reviewed by: </b><%= review.user.first_name.capitalize %> <%= review.user.last_name.first.capitalize %>. <%= "from #{review.user.organization}" if review.user.organization != "" %>
        </p>
        <p><%= review.desc %></p>
      </article>
      <% end %>
    </section>
  </div>

  <% if current_user.try(:admin) == true %>
  <div class='container group'>
    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', :back %>
  </div>
  <% end %>

</div>


  <script>

  $(document).ready(function() {
   $('#nav_reviews').addClass('active');
  });

  $('#product_show_review').hide();
  $("#product_show_review_button").click(function(){
    $("#product_show_review").fadeToggle("slow", "linear");
  })


  </script>