config/routes.rb
Happilabs3::Application.routes.draw do

  resources :products
  resources :reviews
  resources :charges

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users
  resources :reports
  resources :categories
	get "/categories_index" => "Categories#categories_index", as: "categories_index"
  resources :subscribers

  root to: "Pages#index"

  get "/contact" => "Pages#contact", as: "contact"
  get "/200ml" => "Pages#two_hundred_ml", as: "two_hundred_ml"
  get "/1000ml" => "Pages#one_thousand_ml", as: "one_thousand_ml"
  get "/our_people" => "Pages#our_people", as: "our_people"

  get "/jobs" => "Pages#jobs", as: "privacy_policy"
  get "/privacy_policy" => "Pages#privacy_policy", as: "privacy_policy"
  get "/user_agreement" => "Pages#user_agreement", as: "user_agreement"
  get "/lab_sustainability" => "Pages#lab_sustainability", as: "lab_sustainability"

  get "/index" => "Pages#index"
  get "/about_us" => "Pages#about_us", as: "about_us"
  get "/sign_up" => "Pages#sign_up", as: "sign_up"

  get "/voices" => "Pages#voices", as: "voices"
  match '/voices' => 'Pages#create_voice', :as => 'voices', :via => :post
  get "/user_voices" => "Pages#user_voices", :as => "user_voices"
  post "/user_voices" => "Pages#create_user_voice", :as => 'user_voices'
  get "/user_index" => "Pages#user_index", :as => "user_index"
  delete "/user_index/:user_id" => "Pages#delete_user", :as => "delete_user"

  get "/categories/:id/sorted_alphabetically" => "Categories#sorted_alphabetically", :as => "categories_sorted_alphabetically"

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :html_link, :link, :summary, :title
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :validate_admin

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :html_link %><br />
    <%= f.text_field :html_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<section class="about-us group">
  <h1>Editing report</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @report %> |
  <%= link_to 'Back', reports_path %>
</section>

app/views/reports/index.html.erb
<div class="sky-background">
  <div class="container content-container grid group">

    <h1>Reports Index <%= link_to '+ Add a Report', new_report_path, class: "btn btn-success" %></h1>

    <table class="table table-striped">
      <tr>
        <th>Title</th>
        <th>Summary</th>
        <th>Link</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>


    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.title, report.link %></td>
        <td><%= report.summary %></td>
        <td><%= report.link %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

</section>

</div>
</div>

app/views/reports/new.html.erb
<div class="sky-background">
  <div class="container center grid group">

    <section class="about-us group">
      <h1>New report</h1>

      <%= render 'form' %>

      <%= link_to 'Back', reports_path %>
    </section>

</div>
</div>

app/views/reports/show.html.erb
<section class="about-us group">

    <p id="notice"><%= notice %></p>

    <p>
      <b>Title:</b>
      <%= @report.title %>
    </p>

    <p>
      <b>Summary:</b>
      <%= @report.summary %>
    </p>

    <p>
      <b>Link:</b>
      <%= @report.link %>
    </p>

    <p>
      <b>Html link:</b>
      <%= @report.html_link %>
    </p>


    <%= link_to 'Edit', edit_report_path(@report) %> |
    <%= link_to 'Back', reports_path %>
</section>