config/routes.rb
Happilabs3::Application.routes.draw do

  resources :products
  resources :reviews
  resources :charges

  devise_for :users, :controllers => { :registrations => :registrations }
  devise_for :users
  resources :reports
  resources :categories
	get "/categories_index" => "Categories#categories_index", as: "categories_index"
  resources :subscribers

  root to: "Pages#index"

  get "/contact" => "Pages#contact", as: "contact"
  get "/200ml" => "Pages#two_hundred_ml", as: "two_hundred_ml"
  get "/1000ml" => "Pages#one_thousand_ml", as: "one_thousand_ml"
  get "/our_people" => "Pages#our_people", as: "our_people"

  get "/jobs" => "Pages#jobs", as: "privacy_policy"
  get "/privacy_policy" => "Pages#privacy_policy", as: "privacy_policy"
  get "/user_agreement" => "Pages#user_agreement", as: "user_agreement"
  get "/lab_sustainability" => "Pages#lab_sustainability", as: "lab_sustainability"

  get "/index" => "Pages#index"
  get "/about_us" => "Pages#about_us", as: "about_us"
  get "/sign_up" => "Pages#sign_up", as: "sign_up"

  get "/voices" => "Pages#voices", as: "voices"
  match '/voices' => 'Pages#create_voice', :as => 'voices', :via => :post
  get "/user_voices" => "Pages#user_voices", :as => "user_voices"
  post "/user_voices" => "Pages#create_user_voice", :as => 'user_voices'
  get "/user_index" => "Pages#user_index", :as => "user_index"
  delete "/user_index/:user_id" => "Pages#delete_user", :as => "delete_user"

  get "/categories/:id/sorted_alphabetically" => "Categories#sorted_alphabetically", :as => "categories_sorted_alphabetically"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :fair_price, :price_quantity, :first_quality, :second_quality, :third_quality, :youtube, :hl_logo, :paying_photo

  has_many :products

  def products_sorted_by_average_product_rating
    product_array = self.products.map! { |product| product }
    product_array.sort_by {|product| product.reviews.average("rating").to_f}.reverse
  end

  def products_sorted_alphabetically
    product_array = self.products.map! { |product| product }
    product_array.sort_by {|product| product.manufacturer_name}
  end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  # validates :name, :email, :body, :presence => true
  # validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :dept, :org_name
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :distributor_name, :manufacturer_name, :photo, :price, :product_desc, :product_name, :product_num, :recommended, :url

  belongs_to :category
  has_many :reviews

  def to_param
    "#{self.id}-#{self.product_name.parameterize}"
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :html_link, :link, :summary, :title
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :admin_approved, :desc, :make_anonymous, :rating, :user_id, :user_recommended, :product_id

  belongs_to :product
  belongs_to :user

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :active, :email, :first_name, :last_name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :paying_customer, :first_name, :last_name, :admin, :organization_id, :role, :address, :address_2, :city, :zip, :phone, :website_url, :subscription_level, :organization
  # attr_accessible :title, :body

  has_many :user_voices
  # belongs_to :organization
  has_many :reviews

  after_create :send_registration_email

  def send_registration_email
    UserMailer.registration_email(self).deliver
  end

  #write boolean method to see if logged in user is a paying customer
end

app/models/user_voice.rb
class UserVoice < ActiveRecord::Base
  attr_accessible :user_id, :message

  belongs_to :user

  validates :message, :presence => {:message => 'Voice field cannot be blank, Please re-enter your text'}
end

app/models/voice.rb
class Voice
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :content

  # attr_accessible :name, :email, :content

  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :content, :maximum => 5000

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :validate_admin, :only => [:user_index, :delete_user]

  def index
    @message = Message.new
    @user_voice = UserVoice.new
		@categories = Category.order("name ASC")
    @latest_reviews = Review.limit(3).order("created_at DESC")
  end

  def about_us

  end

  def sign_up

  end

  def voices
    @message = Message.new
  end

  def create_voice
    @message = Message.new(params[:message])

    if @message.valid?
      email = PagesMailer.new_message(@message)
      email.deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

  def user_voices
    @user_voices = UserVoice.all
  end

  def create_user_voice
    @user_voice = UserVoice.new(params[:user_voice])

    respond_to do |format|
      if @user_voice.save
        format.html { redirect_to root_path, notice: 'Voice was recorded. Nice job!' }
        format.json { render json: @user_voice, status: :created, location: @user_voice}
      else
        format.html { render 'index', notice: "Voice did not save, please try again" }
        format.json { render json: @user_voice.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_index
    @users = User.all.sort_by {|user| user.id }
  end

  def delete_user
    user = User.find_by_id(params[:user_id])
    user.destroy

    redirect_to user_index_url
  end

  def contact

  end

  def two_hundred_ml

  end

  def one_thousand_ml

  end

  def our_people

  end

  def jobs

  end

  def privacy_policy

  end

  def user_agreement

  end

  def lab_sustainability

  end

end

app/controllers/voices_controller.rb
class VoicesController

    def new
      @voice = Voice.new
    end

    def create
      @voice = Voice.new(params[:voice])
      if @voice.valid?
        # TODO send message here
        redirect_to root_url, notice: "Message sent! Thank you for contacting us."
      else
        render "new"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappiLabs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	
	<meta name="title" content="Happilabs: virtual lab managers who specialize in lab shopping, purchasing, procurement, quality and sustainability ratings, reviews, reports, and consulting consultants for happy lab managers about scientific products, management, and lab supplies">
	<meta name="description" content="HappiLabs provides affordable virtual lab managers for small academic labs and biotech companies. Happy scientists is our goal.">
  <meta name="keywords" content="happilabs, happi labs, happy labs, happy scientists, quality, sustainability, price comparison, research, lab supplies, lab equipment scientific products, reviews, ratings, suppliers, lab manager">
  <meta name="author" content="Tom Ruginis">

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42727054-1', 'happilabs.org');
  ga('send', 'pageview');

</script>
</head>
    <!-- navbar-fixed-top -->
      <div class="navbar navbar-fixed-top navbar-inverse" id="top-nav">
    <!-- INNER-->
        <div class="navbar-inner">
          <div class="container">

      <!-- Collapse button -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

                  <!-- LOGO -->
                  <a class="brand" href="/">
                    <img src="/happilabs_logo_blueback_xl.png" alt="happilabs logo" title="Welcome to HappiLabs for scientists and lab managers" class="logo-shrink">
                  <!-- <span><span class="yellow">Happi</span>Labs<span style="color:#898989">.org</span></span> -->
                  </a>

         <!-- TOP NAVIGATION-->
         <div id="main-nav" class="scroller-spy">
          <nav class="nav-collapse collapse" >
            <ul class="nav pull-right" id="nav">
              <!-- #TODO: make active page highlighted- can use class="active" but needs to be dynamic -->
              <li id="about"><%= link_to "About HL", about_us_path %></li>
              <!-- <li id= "nav_reviews"><%= link_to "Lab reviews", categories_path %></li> -->
              <li id="sign_up"><%= link_to "Services", sign_up_path %></li>
              <li id="contact"><%= link_to "Contact", contact_path %></li>
              <li id="contact"><a href="http://happilabs.wordpress.com/">Blog</a></li>

              <!-- <li>
                  <div>
                    <div id="user_nav">
                      <ul class="whoareyou">
                        <%# if user_signed_in? %>
                        <li><%#= link_to 'Profile', edit_user_registration_path %></li>
                        <li><%#= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                        <%# else %>
                        <li><%#= link_to "Sign up", new_user_registration_path %></li>
                        <li><%#= link_to "Login", new_user_session_path %></li>
                        <%# end %>
                      </ul>
                    </div>
                  </div>
              </li> -->

            </ul>
          </nav>
          </div>

          </div>
        </div>
      </div>
<body>

<%= yield %>


</body>
  <footer>
        <div class="footer-col">
          <a class="twitter-timeline" href="https://twitter.com/HappiLabs_org" data-widget-id="344562470310010880">Tweets by @HappiLabs_org</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


        </div>
      <!-- <div class="footer-col">
        <img src="img/cloud.png" alt="HappiLabs community" class="footer-cloud">
      </div> -->
      <div class="footer-col">
        <h5>About HappiLabs</h5>
        <ul>
          <li><%= link_to "What We Do", about_us_path %></li>
          <li><%= link_to "How We Do It", about_us_path(anchor: "how_we_do_it") %></li>
          <li><%= link_to "Why We Do It", about_us_path(anchor: "why_we_do_it") %></li>
          <li><%= link_to "Read about Our People", our_people_path %></li>
          <li><%= link_to "Privacy Policy", privacy_policy_path   %></li>
          <li><a href="http://www.happilabs.org/jobs">Science Jobs</a></li>
        </ul>
      </div>

      <div class="footer-col">
        <h5>Happy Services</h5>
        <ul>
          <li><a href="http://happilabs.wordpress.com/">FREE advice at our blog</a></li>
          <li><%= link_to "Reviews about Lab Supplies", categories_path %></li>
          <li><%= link_to "Lab Shopping Consultants", two_hundred_ml_path %></li>
          <li><%= link_to "Hire a Virtual Lab Manager", one_thousand_ml_path %></li>
        </ul>
      </div>
      <div class="footer-col">
        <h5>Receive our newsletter</h5>
            <ul>

              <li id="newsletter-text">For content about lab shopping, funding, jobs, and startups</li>
            </ul>
            <ul>
              <!-- <li>Receive our newsletter</li> -->
              <% @subscriber = Subscriber.new %>
              <%= form_for(@subscriber) do |f| %>
                <% if @subscriber.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

                    <ul>
                    <% @subscriber.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">

                  <%= f.text_field :first_name, placeholder: "Name" %>
                </div>

                <div class="field">
                  <%= f.text_field :email, placeholder: "Email" %>
                </div>

                <div class="actions">
                  <%= f.submit "Submit", :class => "btn btn-success" %>
                </div>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>

  </footer>
</html>

app/views/pages/_signup.html.erb
<%= form_for(@user) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit "Subscribe", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/pages/about_us.html.erb
<div class="small-grid group">
    <!-- SERVICE SIDE-->
  <div class="content-container">
    <div id="mission-center">

                <h4>
                <span id="about-mission-highlight"><span class="yellow">OUR MISSION:</span><br> to improve the <span class="yellow">happiness</span> of scientists & <br> the <span class="yellow">quality</span> of their research</span></h4>
    </div>

    <h2>WHAT WE DO</h2>
    
    <div id="vimeo">
        <p class="second-p">Our Founder, Tom, explains the HL story at Technori Pitch July 2013...</p>
        <iframe src="//player.vimeo.com/video/71992400" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    
    </div>
    <div class="container group">
      <img src="abouthl.png" alt="data for scientists" title="use data to save time and money" class="about-image">
      <div class="text-right-img">
        <p>
          HappiLabs, LLC was established in Chicago in 2013. We are a purchasing organization that provides virtual lab manager services with a speciality of shopping for scientific lab supplies, chemicals/reagents, and equipment (think...personal shopper for scientists).
        </p>
        <p>
          We noticed that scientists do not have resources available to make informed purchasing decisions about lab supplies and all the companies who sell them.</p> 
          
          <p>What is a fair price? Who has the best quality?</p>

          <p>This results in <strong>wasted time and funding and false data</strong>. Therefore, our goal is to be a reliable resource for making quick, informed decisions about lab supplies.
        </p>
        <p>
          We evaluate lab supplies & equipment, and the companies who make & sell them, on 3 categories:
        </p>
        <div class="evaluation">
            <ol class="group" id="about-evaluation">
              <li>
                <div class="evaluation-category">
                  <img src="money-icon.png" alt="What is the price?" title="lab managers fair price supplies" class="eval-photo">
                  <p>Price</p>
                </div>
              </li>
              <li>
                <div class="evaluation-category">
                  <img src="science-consumable-quality-star.png" alt="Quality ratings" title="lab managers high quality supplies" class="eval-photo">
                  <p>Quality</p>
                </div>
              </li>
             <!--  <li>
                <div class="evaluation-category">
                  <img src="life-science-customer_service.png" alt="customer service" title="life science friendly service" class="eval-photo">
                  <p>Service</p>
                </div>
              </li> -->
              <li id="green-font">
                <div class="evaluation-category">
                  <img src="sustainability-happilabs.png" alt="protect our home planet" title="life science sustainability ratings" class="eval-photo">
                  <p id="green-font">Sustainability</p>
                </div>
              </li>
            </ol>
        </div>
        
        <p>
          How much time do you spend shopping for lab supplies? STOP! <strong>Focus on your science</strong> and let us focus on your shopping. The less you have to think about this stuff, the lower your stress, and the happier you’ll be.
        </p>
         <div class="">
            <%= link_to "Hire a Virtual Lab Manager", one_thousand_ml_path, class: "btn btn-danger btn-how" %>
          </div>
      </div>
    </div>
  </div>

</div>

      <!-- **************  HOW WE DO IT **************** -->



  <div class="content-container about-us sky-background group" id="how_we_do_it">
    <h2>HOW WE DO IT</h2>

    <div class="container group">
      <div class="text-left-img">

          <p>
          We have organized a growing <span class="important">community</span> of scientists who share opinions about the quality of their life in the lab. They submit ratings and reviews about products, services, and companies they interact with.
          </p>

          <div class="">
            <%= link_to "Meet our scientists!", our_people_path, class: "btn btn-danger btn-how" %>
          </div>

          <p>To supplement user reviews, HappiLabs' scientists perform <strong>independent research</strong> on companies by scanning their website and catalogues, collecting quality documentation, and performing interviews.</p>
          <p>
          At HappiLabs Central, a <%= link_to "team of PhDs and grad students", our_people_path   %> organize, analyze, and summarize the data. Then we use the data to become <strong>awesome shoppers and lab managers</strong>. We also share some data in print and online reports, email newsletters, and <a href="https://twitter.com/HappiLabs_org">Twitter.</a></p>

          <p>This <span class="important">equilibrium of data transfer</span> helps us create a more efficient research enterprise by <strong>empowering scientists</strong> to make intelligent purchasing decisions, resulting in money and time savings.
          </p>

      </div>

      <!-- <img src="savings2.png" alt="data for scientists" title="use data to save time and money" class="graph-image"> -->
       <div id="community-graphic">
         <img src="happy_virtual_lab_managers.png" alt="data for scientists" title="We are a community of scientists" class="tom-image">
         <p>Created by: Anthony Salvagno, PhD</p>
      </div>
    </div>
  </div>


     <!-- **************  WHY WE DO IT **************** -->



  <div class="about-us content-container small-grid group" id="why_we_do_it">
      <div class="page-heading">
        <h2>WHY WE DO IT</h2>
        <div class="contact-us">
          <p>The scientific community has problems that need solving.</p>
        </div>
      </div>

    <div class="container group">

      <div class="row-fluid">

        <div class="why-box group">

          <h3>Contaminated Experiments</h3>

          <!-- <img src="ruined-experiments.jpg" alt="poor quality control contaminates experiments" title="contaminated plastics ruin your experiments" class="img-holder"> -->

            <h4>Reports suggest that low-quality supplies are contaminating your experiments:</h4>
                <ul>
                  <li><a href="http://www.nature.com/news/2010/100423/full/news.2010.200.html">Plastics Hamper DNA Assays</a></li>
                  <li><a href="http://www.sciencemag.org/content/322/5903/917.short">Contaminants Leach from Plasticware</a></li>
                  <li><a href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0062325">Dispensing Processes Impact Biological Activity</a></li>
                </ul>
            <h4><span class="why-solution">SOLUTION</span>: Our research identifies low-quality supplies to prevent these problems in your lab.</h4>

                <!-- <div class="goals">
                  <h4>Are you using low-quality lab supplies?</h4>
                </div> -->
        </div>

        <div class="why-box group">

          <h3>NIH is asking for help</h3>

          <!-- <img src="nih-budget-crunch.jpg" alt="NIH seeks advice during fiscal time" title="NIH asks for help" class="img-holder"> -->

            <h4>With shrinking budgets, the NIH is asking for help:</h4>
              <ul>
                <li>"[The NIH is] interested in your ideas about how best to manage in complex budgetary times."</li>
                <li><a href="http://nexus.od.nih.gov/all/2011/10/17/how-do-you-think-we-should-manage-science-in-fiscally-challenging-times/">Read more at NIH.gov</a></li>
              </ul>
              <br>
          <h4><span class="why-solution">SOLUTION</span>: We provide <a href="http://www.happilabs.org/sign_up">resources to help scientists save money on lab supplies</a></h4>

              <!-- <div class="goals">
                <h4>Do you need help managing your lab?</h4>
              </div> -->
        </div>

        <div class="why-box group">

          <h3>Not Enough Jobs</h3>

          <!-- <img src="unhappy_face.jpg" alt="unhappy grad student survey" class="first-why-img"> -->

            <h4>Too many PhD's and a lack of alternative career training are creating an unhappy lab environment for grad students and postdocs: 
            </h4>
            <ul>
                <li><a href="http://www.nature.com/nature/journal/v472/n7343/full/472259b.html">Dismal job prospects for PhD's</a></li>
                <li><a href="http://www.nature.com/naturejobs/science/articles/10.1038/nj7357-533a">Survey: Grad Students are Unhappy</a></li>
            </ul>

            <h4><span class="why-solution">SOLUTION</span>: We created internships to help scientists find jobs away from the bench. <a href="http://www.happilabs.org/jobs">View our jobs</a>. 
            </h4>

            <!-- <div class="goals">
              <h4>Are you one of these grad students?</h4>
            </div> -->
        </div>

      <%= link_to "Become a Member", sign_up_url, class: "btn btn-large btn-success btn-why" %>
    </div>
  </div>


<script>
$(document).ready(function() {
  $('#about').addClass('active');
});
</script>

app/views/pages/lab_sustainability.html.erb
<div class="container">
  <h1>Lab Sustainability</h1>
</div>

app/views/pages/sign_up.html.erb
<div class="grid">
  <div class="content-container subscribe-us group">

      <div class="page-heading">
        <h2>SERVICES</h2>
        <h4>We provide affordable services to reduce costs and increase efficiency for academic and biotech labs.</h4>
        <h4>What volume of help would you like?</h4>
      </div>

      <h5>Happy Testimonials</h5>
        <div class="testimonial group">
            
           
            <p class="second-p">"I am happy that a service like this exists; <strong>it makes my job easier.</strong>"</p>
            <p><a href="http://www.rrc.uic.edu/supplycenter/contact"><em>Jenny Beck, Director of the Research Resource Center at University of IL-Chicago</em> (contact Jenny if you have questions)</a></p>
          </div>
          <div class="testimonial group">
        
            <p class="second-p"><span class="testimonial-highlight">"Three words that describe my experience with HappiLabs: <strong>satisfaction, satisfaction, satisfaction</strong>."</p>

            <p><a href="http://www.perlsteinlab.com/"><em>Ethan Perlstein, PhD and CEO of PerlsteinLab.com</em></a></p>
          </div>

        <div class="container" id="showprice">
          <div class="row-fluid text-center">
            <div class="span4 feature-box price-feature-box">
              <div class="pricing-table price-box">
                    <div class="price-header"  id="price10">
                      <span>10 &#181;L</span>

                    </div>
                    <div class="pricing-table-header">

                        <img src="happilabs_hl_logo_xl.png" alt="10ul service read product reviews for scientists" title="read and write lab supply product ratings and reviews for happy scientists" class="price-photo">
                    </div>

                    <div class="pricing-table-features">
                        <ul class="subscribe-list">
                          <li>Visit the <strong>HappiLabs Blog</strong></li>
                          <li>Useful tips for managing lab shopping and finding best pricing</li>
                        </ul>

                        <!-- <p>Monthly newsletter with useful resources for scientists</p>
                        <p>Ability to review products, companies, and your lab.</p>
                        <p></p> -->
                        <h5 class="sub-price">FREE</h5>
                    </div>
                    <div class="pricing-table-sign-up">
                        <%= link_to "Take me to the blog", categories_path, class: "btn btn-large btn-block btn-success btn-price"  %>
                    </div>
              </div>
            </div>


            <div class="span4 feature-box price-feature-box ">
              <div class="pricing-table price-box">

                <div class="price-header" id="price200">
                      <span>200 &#181;L</span>

                </div>
                <div class="pricing-table-header">

                  <img src="ourpeople/Raudel_Sandoval_PhD_HappiLabs_Scientific_Consultant.JPG" alt="200ul subscription to happi reports" title="subscribe to happi labs reports about the price and quality of lab supplies" class="price-photo">

                </div>

                    <div class="pricing-table-features">
                        <ul class="subscribe-list">
                          <li>Subscribe to our <strong>Lab Shopping Consultants</strong></li>
                          <li>Receive a one-time lab purchasing and spending analysis</li>
                        </ul>
                        <h5 class="sub-price"><span id="small-price">Starting at </span>$250<span id="small-price">/month</span></h5>
                    </div>
                    
                    <div class="pricing-table-sign-up">
                        <%= link_to "Learn more!", two_hundred_ml_path, class: "btn btn-large btn-premium btn-block btn-price" %>
                    </div>
                  </div>
            </div>


          <div class="span4 feature-box price-feature-box ">
              <div class="pricing-table price-box">
                  <div class="price-header"  id="price1000">
                      <span>1000 &#181;L</span>
                  </div>

                  <div class="pricing-table-header">
                    <img src="happy_virtual_lab_managers.png" alt="10ul subscription for happilabs lab manager report" title="hire a happy lab manager consultant to save money and time" class="price-photo">
                  </div>

                  <div class="pricing-table-space"></div>
                    <div class="pricing-table-features">
                        <!-- <h4>Rent-a-lab-manager to</h4> -->
                        <ul class="subscribe-list">
                          <li>Hire a <strong>Virtual Lab Manager</strong></li>
                          <li>Help with shopping, purchasing & finances</li>
                        </ul>
                         <h5 class="sub-price"><span id="small-price">Starting at </span>$65<span id="small-price">/hour</span></h5>
                    </div>

                    <div class="pricing-table-sign-up">
                        <%= link_to "Learn more...", one_thousand_ml_path, class: "btn btn-large btn-premium btn-block btn-price" %>
                    </div>
                  </div>
              </div>
          </div>
        </div>
        
  </div>
</div>

<script>
$(document).ready(function() {
  $('#sign_up').addClass('active');
});
</script>

app/views/pages/upgrade.html.erb
<% #TODO - Figure out if we want an upgrade page or not. Probably not.  %>

app/views/pages/user_index.html.erb
<div class="sky-background">
  <div class="container content-container grid group">

  <h1>User Index</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Subscription Level</th>
        <th>Organization</th>
        <th>Sign-in Count</th>
        <th>Last Sign In</th>
        <th>Delete?</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.subcription_level %></td>
        <td><%= user.organization %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.last_sign_in_at.strftime("%b %d, %Y %l:%M%p ") %></td>
        <td><%= button_to 'Delete?', delete_user_path(user.id), :method => 'delete', class: "btn",  :confirm => 'Are you sure?' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/pages/user_voices.html.erb
<div class="about-us">
  <h1>User Voices</h1>
  <ol>
    <% @user_voices.reverse.each do |user_voice| %>
      <li>
        <h3><%= user_voice.user.first_name %><%= user_voice.user.first_name %></h3>
        <h4>"<%= user_voice.message %>"</h4>
        <h6><%= mail_to user_voice.user.email %></h6>
      </li>
    <% end %>
  </ol>
</div>